<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Self Reflection Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #222;
            font-size: 13px;
            line-height: 1.6;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #222;
            padding-bottom: 10px;
            margin-bottom: 25px;
        }

        .header h1 {
            margin: 0;
            font-size: 22px;
        }

        .section {
            margin-bottom: 22px;
        }

        .section h2 {
            font-size: 16px;
            border-bottom: 1px solid #ccc;
            padding-bottom: 5px;
        }

        .summary-box {
            border: 1px solid #ddd;
            padding: 12px;
            margin-bottom: 10px;
            background: #f7f7f7;
        }

        .reflection-card {
            border: 1px solid #ddd;
            padding: 12px;
            margin-bottom: 12px;
        }

        .label {
            font-weight: bold;
        }

        .footer {
            margin-top: 30px;
            font-size: 11px;
            color: #666;
            text-align: center;
        }
    </style>
</head>
<body>

<div class="header">
    <h1>AI-Based Self Reflection Report</h1>
    <p>Generated on {{ $generatedAt }}</p>
</div>

<div class="section">
    <h2>User Summary</h2>
    <div class="summary-box">
        <p><span class="label">Name:</span> {{ $user->name }}</p>
        <p><span class="label">Email:</span> {{ $user->email }}</p>
        <p><span class="label">Total Reflections:</span> {{ $totalReflections }}</p>
        <p><span class="label">Dominant Emotion:</span> {{ ucfirst($dominantEmotion) }}</p>
        <p><span class="label">Dominant Pattern:</span> {{ ucfirst($dominantPattern) }}</p>
    </div>
</div>

<div class="section">
    <h2>Reflection History & Insights</h2>

    @forelse($reflections as $reflection)
        <div class="reflection-card">
            <p><span class="label">Date:</span> {{ $reflection->created_at->format('d M Y, h:i A') }}</p>

            <p><span class="label">Reflection:</span></p>
            <p>{{ $reflection->reflection_text }}</p>

            <p>
                <span class="label">Emotion:</span>
                {{ ucfirst($reflection->emotionAnalysis?->emotion ?? 'N/A') }}
            </p>

            <p>
                <span class="label">Sentiment:</span>
                {{ ucfirst($reflection->emotionAnalysis?->sentiment ?? 'N/A') }}
            </p>

            <p>
                <span class="label">Confidence Score:</span>
                {{ $reflection->emotionAnalysis?->confidence_score ?? 'N/A' }}%
            </p>

            <p>
                <span class="label">Pattern Detected:</span>
                {{ ucfirst($reflection->insight?->pattern_detected ?? 'N/A') }}
            </p>

            <p>
                <span class="label">Generated Insight:</span>
                {{ $reflection->insight?->generated_insight ?? 'N/A' }}
            </p>
        </div>
    @empty
        <p>No reflections available.</p>
    @endforelse
</div>

<div class="section">
    <h2>Important Note</h2>
    <p>
        This report is generated by an AI-based self-reflection support system.
        It is not a medical diagnosis, therapy replacement, or clinical assessment.
        Users with serious emotional or mental health concerns should seek appropriate professional support.
    </p>
</div>

<div class="footer">
    AI-Based Self Reflection and Relationship Insight System
</div>

</body>
</html>